-- MySQL Script generated by MySQL Workbench
-- Tue 10 Mar 2020 06:11:21 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patike_banka_1` ;
USE `patike_banka_1`;

-- -----------------------------------------------------
-- Table `bank`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons` (
  `jmbg` VARCHAR(13) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`jmbg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`businesses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businesses` (
  `merchant_id` VARCHAR(30) NOT NULL,
  `merchant_password` VARCHAR(100) NULL,
  PRIMARY KEY (`merchant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`persons_business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons_business` (
  `persons_jmbg` VARCHAR(13) NOT NULL,
  `businesses_merchant_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`persons_jmbg`, `businesses_merchant_id`),
  INDEX `fk_persons_has_table1_table11_idx` (`businesses_merchant_id` ASC),
  INDEX `fk_persons_has_table1_persons_idx` (`persons_jmbg` ASC),
  CONSTRAINT `fk_persons_has_table1_persons`
    FOREIGN KEY (`persons_jmbg`)
    REFERENCES `persons` (`jmbg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_has_table1_table11`
    FOREIGN KEY (`businesses_merchant_id`)
    REFERENCES `businesses` (`merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `number` VARCHAR(10) NOT NULL,
  `balance` DOUBLE NULL,
  `reserved` DOUBLE NULL DEFAULT 0,
  `persons_jmbg` VARCHAR(13) NULL,
  `businesses_merchant_id` VARCHAR(30) NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cards` (
  `pan` VARCHAR(16) NOT NULL,
  `account_number` VARCHAR(10) NOT NULL,
  `pin` VARCHAR(4) NULL,
  `issue_date` DATE NOT NULL,
  `expiry_date` DATE NOT NULL,
  `cardholder_name` VARCHAR(100) NULL,
  `security_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`pan`),
  INDEX `fk_cards_account1_idx` (`account_number` ASC),
  CONSTRAINT `fk_cards_account1`
    FOREIGN KEY (`account_number`)
    REFERENCES `account` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`transations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(10) NOT NULL,
  `debit` DOUBLE NULL DEFAULT 0,
  `credit` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`id`, `account_number`),
  INDEX `fk_transations_account1_idx` (`account_number` ASC),
  CONSTRAINT `fk_transations_account1`
    FOREIGN KEY (`account_number`)
    REFERENCES `account` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `amount` DOUBLE NOT NULL DEFAULT 0,
  `success_url` VARCHAR(100) NULL,
  `failed_url` VARCHAR(100) NULL,
  `error_url` VARCHAR(100) NULL,
  `businesses_merchant_id` VARCHAR(30) NOT NULL,
  `payment_url` VARCHAR(256) NULL,
  `paid` INT DEFAULT 0,
  `merchant_order_id` INT NOT NULL,
  `acquirer_timestamp` DATETIME,
  PRIMARY KEY (`order_id`, `businesses_merchant_id`),
  INDEX `fk_orders_businesses1_idx` (`businesses_merchant_id` ASC),
  CONSTRAINT `fk_orders_businesses1`
    FOREIGN KEY (`businesses_merchant_id`)
    REFERENCES `businesses` (`merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bank`.`persons`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `persons` (`jmbg`, `name`, `surname`, `address`, `email`, `phone`) VALUES ('8888888888888', 'Petar', 'Petrović', 'Zmaj Jovina 28', 'petarpetrovic@mail.nn', '');
INSERT INTO `persons` (`jmbg`, `name`, `surname`, `address`, `email`, `phone`) VALUES ('1111111111111', 'Milena', 'Milenković', 'Laze Kostića 12', 'milenamilenkovic@mail.nn', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bank`.`businesses`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `businesses` (`merchant_id`, `merchant_password`) VALUES ('NS2100508PAT', 'merchpassword123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bank`.`persons_business`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `persons_business` (`persons_jmbg`, `businesses_merchant_id`) VALUES ('8888888888888', 'NS2100508PAT');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bank`.`account`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `account` (`number`, `balance`, `reserved`, `persons_jmbg`, `businesses_merchant_id`) VALUES ('1234567890', 10000000, 100000, NULL, 'NS2100508PAT');
INSERT INTO `account` (`number`, `balance`, `reserved`, `persons_jmbg`, `businesses_merchant_id`) VALUES ('0987654321', 150000, 0, '8888888888888', NULL);
INSERT INTO `account` (`number`, `balance`, `reserved`, `persons_jmbg`, `businesses_merchant_id`) VALUES ('1324354657', 45000, 5321, '1111111111111', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bank`.`cards`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `cards` (`pan`, `account_number`, `pin`, `issue_date`, `expiry_date`, `cardholder_name`, `security_code`) VALUES ('1234432156788790', '0987654321', '1234', '2020-01-01', '2022-01-01', 'Petar Petrovic', '123');
INSERT INTO `cards` (`pan`, `account_number`, `pin`, `issue_date`, `expiry_date`, `cardholder_name`, `security_code`) VALUES ('1719354780010981', '1324354657', '4321', '2020-01-01', '2022-01-01', 'Milena Milenkovic', '321');

COMMIT;

